using Fmc.Domain.Entities;

namespace Fmc.Infrastructure.Persistence;

/// <summary>20 cafeterías demo en CABA con coords, tier y assets de <c>Api/SeedAssets</c>.</summary>
internal static class CabaCatalogSeed
{
    internal sealed record CatalogCafe(
        Guid CafeId,
        Guid EnterpriseId,
        Guid PhotoId,
        string Name,
        string Description,
        string Address,
        double Latitude,
        double Longitude,
        EnterpriseSubscriptionTier Tier,
        int DiscountPercent,
        string EnterpriseEmail,
        string PhotoStorageKey,
        string? AvatarStorageKey);

    internal static readonly string[] PhotoAssets =
    [
        "seed-palermo-barra.jpg",
        "seed-san-telmo-patio.jpg",
        "seed-recoleta-detalle.jpg",
        "seed-caballito-local.jpg",
        "seed-palermo-interior.jpg",
        "seed-recoleta-frente.jpg",
        "seed-caballito-visita.jpg",
    ];

    internal static readonly CatalogCafe[] Cafes =
    [
        new(
            DataSeeder.CafePremiumId,
            DataSeeder.EnterprisePremiumId,
            Guid.Parse("c1111111-1111-4111-8111-111111111102"),
            "FMC Seed — Palermo (Premium)",
            "Espacio luminoso en Palermo con barra de especialidad y wifi estable.",
            "Thames 1500, Palermo, CABA",
            -34.5875, -58.4250,
            EnterpriseSubscriptionTier.Premium, 15,
            "enterprise-premium@seed.fmc",
            "seed-palermo-barra.jpg",
            "seed-palermo-barra.jpg"),
        new(
            DataSeeder.CafeStandardId,
            DataSeeder.EnterpriseStandardId,
            Guid.Parse("c2222222-2222-4222-8222-222222221101"),
            "FMC Seed — San Telmo (Standard)",
            "Café de barrio en San Telmo, patio al aire libre y medialunas caseras.",
            "Defensa 800, San Telmo, CABA",
            -34.6210, -58.3730,
            EnterpriseSubscriptionTier.Standard, 8,
            "enterprise-standard@seed.fmc",
            "seed-san-telmo-patio.jpg",
            null),
        new(
            DataSeeder.CafeRecoletaId,
            DataSeeder.EnterpriseRecoletaId,
            Guid.Parse("c3333333-3333-4333-8333-333333331102"),
            "FMC Seed — Recoleta (Premium)",
            "Local premium en Recoleta, ideal para reuniones y brunch.",
            "Av. Callao 1500, Recoleta, CABA",
            -34.5950, -58.3920,
            EnterpriseSubscriptionTier.Premium, 12,
            "enterprise-recoleta@seed.fmc",
            "seed-recoleta-detalle.jpg",
            "seed-recoleta-detalle.jpg"),
        new(
            DataSeeder.CafeCaballitoId,
            DataSeeder.EnterpriseCaballitoId,
            Guid.Parse("c4444444-4444-4444-8444-444444441101"),
            "FMC Seed — Caballito (Standard)",
            "Cafetería acogedora en Caballito, espresso clásico y precios accesibles.",
            "Río de Janeiro 600, Caballito, CABA",
            -34.6195, -58.4320,
            EnterpriseSubscriptionTier.Standard, 10,
            "enterprise-caballito@seed.fmc",
            "seed-caballito-local.jpg",
            null),
        Cafe(5, "FMC Seed — Belgrano (Premium)",
            "Tostado de origen y pastelería artesanal en Belgrano.",
            "Av. Cabildo 2200, Belgrano, CABA", -34.5635, -58.4580,
            EnterpriseSubscriptionTier.Premium, 14, "enterprise-belgrano@seed.fmc"),
        Cafe(6, "FMC Seed — Villa Crespo (Standard)",
            "Café de especialidad en Villa Crespo, ambiente relajado.",
            "Av. Corrientes 5800, Villa Crespo, CABA", -34.5980, -58.4360,
            EnterpriseSubscriptionTier.Standard, 7, "enterprise-villacrespo@seed.fmc"),
        Cafe(7, "FMC Seed — Almagro (Standard)",
            "Barra de café y desayunos en Almagro.",
            "Av. Medrano 900, Almagro, CABA", -34.6055, -58.4205,
            EnterpriseSubscriptionTier.Standard, 9, "enterprise-almagro@seed.fmc"),
        Cafe(8, "FMC Seed — Boedo (Standard)",
            "Café literario en Boedo, mesas amplias y buen cortado.",
            "Av. Boedo 800, Boedo, CABA", -34.6280, -58.4120,
            EnterpriseSubscriptionTier.Standard, 8, "enterprise-boedo@seed.fmc"),
        Cafe(9, "FMC Seed — Puerto Madero (Premium)",
            "Vista al dique con café de autor y opciones sin lactosa.",
            "Av. Alicia Moreau de Justo 1200, Puerto Madero, CABA", -34.6105, -58.3615,
            EnterpriseSubscriptionTier.Premium, 18, "enterprise-puertomadero@seed.fmc"),
        Cafe(10, "FMC Seed — Núñez (Standard)",
            "Café de barrio en Núñez, cerca del río.",
            "Av. del Libertador 8200, Núñez, CABA", -34.5480, -58.4565,
            EnterpriseSubscriptionTier.Standard, 6, "enterprise-nunez@seed.fmc"),
        Cafe(11, "FMC Seed — Colegiales (Premium)",
            "Micro-tostadero y filtrados en Colegiales.",
            "Av. Federico Lacroze 2800, Colegiales, CABA", -34.5745, -58.4470,
            EnterpriseSubscriptionTier.Premium, 13, "enterprise-colegiales@seed.fmc"),
        Cafe(12, "FMC Seed — Barracas (Standard)",
            "Café industrial-chic en Barracas, ideal para remoto.",
            "Av. Montes de Oca 1200, Barracas, CABA", -34.6420, -58.3695,
            EnterpriseSubscriptionTier.Standard, 8, "enterprise-barracas@seed.fmc"),
        Cafe(13, "FMC Seed — La Boca (Standard)",
            "Café colorido en La Boca, ambiente porteño auténtico.",
            "Av. Almirante Brown 900, La Boca, CABA", -34.6345, -58.3635,
            EnterpriseSubscriptionTier.Standard, 7, "enterprise-laboca@seed.fmc"),
        Cafe(14, "FMC Seed — Villa Urquiza (Premium)",
            "Brunch y specialty coffee en Villa Urquiza.",
            "Av. Triunvirato 4500, Villa Urquiza, CABA", -34.5755, -58.4885,
            EnterpriseSubscriptionTier.Premium, 11, "enterprise-villaurquiza@seed.fmc"),
        Cafe(15, "FMC Seed — Flores (Standard)",
            "Café familiar en Flores, buen balance precio-calidad.",
            "Av. Rivadavia 6800, Flores, CABA", -34.6295, -58.4635,
            EnterpriseSubscriptionTier.Standard, 9, "enterprise-flores@seed.fmc"),
        Cafe(16, "FMC Seed — Parque Patricios (Standard)",
            "Espacio tranquilo en Parque Patricios para trabajar.",
            "Av. Caseros 3100, Parque Patricios, CABA", -34.6385, -58.4045,
            EnterpriseSubscriptionTier.Standard, 8, "enterprise-parquepatricios@seed.fmc"),
        Cafe(17, "FMC Seed — Retiro (Premium)",
            "Café express y pastelería francesa en Retiro.",
            "Av. Santa Fe 900, Retiro, CABA", -34.5955, -58.3755,
            EnterpriseSubscriptionTier.Premium, 16, "enterprise-retiro@seed.fmc"),
        Cafe(18, "FMC Seed — Monserrat (Standard)",
            "Café histórico en Monserrat, a pasos del Obelisco.",
            "Av. de Mayo 1200, Monserrat, CABA", -34.6095, -58.3845,
            EnterpriseSubscriptionTier.Standard, 10, "enterprise-monserrat@seed.fmc"),
        Cafe(19, "FMC Seed — Balvanera (Standard)",
            "Cortado clásico y facturas en Balvanera.",
            "Av. Corrientes 3200, Balvanera, CABA", -34.6035, -58.4105,
            EnterpriseSubscriptionTier.Standard, 7, "enterprise-balvanera@seed.fmc"),
        Cafe(20, "FMC Seed — Saavedra (Premium)",
            "Café de barrio premium en Saavedra con terraza.",
            "Av. Dr. Ricardo Balbín 4200, Saavedra, CABA", -34.5555, -58.4895,
            EnterpriseSubscriptionTier.Premium, 12, "enterprise-saavedra@seed.fmc"),
        Cafe(21, "FMC Seed — Chacarita (Premium)",
            "Brunch de autor y filtrados en Chacarita.",
            "Av. Federico Lacroze 3800, Chacarita, CABA", -34.5885, -58.4555,
            EnterpriseSubscriptionTier.Premium, 13, "enterprise-chacarita@seed.fmc"),
        Cafe(22, "FMC Seed — Microcentro (Standard)",
            "Café rápido en Microcentro, ideal para pausa laboral.",
            "Av. Corrientes 300, San Nicolás, CABA", -34.6037, -58.3816,
            EnterpriseSubscriptionTier.Standard, 9, "enterprise-microcentro@seed.fmc"),
    ];

    internal static int Count => Cafes.Length;

    private static CatalogCafe Cafe(
        int index,
        string name,
        string description,
        string address,
        double latitude,
        double longitude,
        EnterpriseSubscriptionTier tier,
        int discountPercent,
        string enterpriseEmail)
    {
        var photoKey = PhotoAssets[(index - 1) % PhotoAssets.Length];
        var avatarKey = tier == EnterpriseSubscriptionTier.Premium ? photoKey : null;
        return new CatalogCafe(
            SeedGuid(index, "1101"),
            SeedGuid(index, "1201"),
            SeedGuid(index, "1102"),
            name,
            description,
            address,
            latitude,
            longitude,
            tier,
            discountPercent,
            enterpriseEmail,
            photoKey,
            avatarKey);
    }

    private static Guid SeedGuid(int index, string suffix) =>
        Guid.Parse($"c{index:D7}-1111-4111-8111-{suffix.PadLeft(12, '0')}");
}
