// <auto-generated />
using System;
using Fmc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fmc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615201414_ConsumerFavoritesAndEnterpriseCoupons")]
    partial class ConsumerFavoritesAndEnterpriseCoupons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Fmc.Domain.Entities.Cafeteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("ListingActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cafeterias");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.CafeteriaPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CafeteriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CafeteriaId");

                    b.ToTable("CafeteriaPhotos");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.CafeteriaReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CafeteriaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoStorageKey")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CafeteriaId");

                    b.HasIndex("CafeteriaId", "AuthorUserId", "AuthorRole")
                        .IsUnique();

                    b.ToTable("CafeteriaReviews");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.ConsumerFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CafeteriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsumerUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CafeteriaId");

                    b.HasIndex("ConsumerUserId");

                    b.HasIndex("ConsumerUserId", "CafeteriaId")
                        .IsUnique();

                    b.ToTable("ConsumerFavorites");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.ConsumerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarStorageKey")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ConsumerUsers");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.EnterpriseCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CafeteriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixedAmountArs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CafeteriaId");

                    b.HasIndex("CafeteriaId", "Code")
                        .IsUnique();

                    b.ToTable("EnterpriseCoupons");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.EnterpriseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CafeteriaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CafeteriaId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("EnterpriseUsers");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.CafeteriaPhoto", b =>
                {
                    b.HasOne("Fmc.Domain.Entities.Cafeteria", "Cafeteria")
                        .WithMany()
                        .HasForeignKey("CafeteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cafeteria");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.CafeteriaReview", b =>
                {
                    b.HasOne("Fmc.Domain.Entities.Cafeteria", "Cafeteria")
                        .WithMany()
                        .HasForeignKey("CafeteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cafeteria");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.ConsumerFavorite", b =>
                {
                    b.HasOne("Fmc.Domain.Entities.Cafeteria", "Cafeteria")
                        .WithMany()
                        .HasForeignKey("CafeteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fmc.Domain.Entities.ConsumerUser", "ConsumerUser")
                        .WithMany()
                        .HasForeignKey("ConsumerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cafeteria");

                    b.Navigation("ConsumerUser");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.EnterpriseCoupon", b =>
                {
                    b.HasOne("Fmc.Domain.Entities.Cafeteria", "Cafeteria")
                        .WithMany()
                        .HasForeignKey("CafeteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cafeteria");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.EnterpriseUser", b =>
                {
                    b.HasOne("Fmc.Domain.Entities.Cafeteria", "Cafeteria")
                        .WithOne("EnterpriseUser")
                        .HasForeignKey("Fmc.Domain.Entities.EnterpriseUser", "CafeteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cafeteria");
                });

            modelBuilder.Entity("Fmc.Domain.Entities.Cafeteria", b =>
                {
                    b.Navigation("EnterpriseUser");
                });
#pragma warning restore 612, 618
        }
    }
}
